<a href="https://colab.research.google.com/github/Agoston03/Machine-Learning-VIMIMA05/blob/main/ML_2026_lab2_linreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear models for regression

In the first part of the session, you will generate datasets and fit linear regression models using the `numpy` and `sklearn` packages. The theoretical background can be found in the lecture notes; we suggest to follow it closely.


## Data generation

First, we demonstrate linear regression on a toy dataset we generate ourselves, with a linear relationship between inputs and outputs with some additional noise.

**Exercise 1.** Generate a linear dataset with additive Gaussian noise.

In more detail:

- Use the [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) function to generate $51$ evenly spaced training inputs from $0$ to $10$ (`x_train`). The result should look something like
```
array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
          2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
          4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
          6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
          8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])
```
- Generate the corresponding labels by computing $w \cdot x + b$ with $w = 0.7$ and $b = 2$, i.e.
```
array([2.  , 2.14, 2.28, 2.42, 2.56, 2.7 , 2.84, 2.98, 3.12, 3.26, 3.4 ,
         3.54, 3.68, 3.82, 3.96, 4.1 , 4.24, 4.38, 4.52, 4.66, 4.8 , 4.94,
         5.08, 5.22, 5.36, 5.5 , 5.64, 5.78, 5.92, 6.06, 6.2 , 6.34, 6.48,
         6.62, 6.76, 6.9 , 7.04, 7.18, 7.32, 7.46, 7.6 , 7.74, 7.88, 8.02,
         8.16, 8.3 , 8.44, 8.58, 8.72, 8.86, 9.  ])
```
Keep in mind that contrary to Python lists, you can perform arithmetic operations and [functions](https://numpy.org/doc/stable/reference/routines.math.html) on `numpy` arrays just as you would on scalars, *i.e.* operations will automatically be applied to all elements of the array.
- Add some random noise to the labels with the [`np.random.randn`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html) function (`y_train`).
- Use the [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) function to generate $100$ evenly spaced test inputs from $0$ to $10$ (`x_test`).
- Plot the training dataset with the [`plt.scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) function.

In [ ]:
from matplotlib import pyplot as plt
import numpy as np

# TODO generate x_train, y_train, x_test
# TODO generate scatterplot from training data (Optional: also plot the ground truth noiseless samples)

## Maximum likelihood estimation

Recall that solving a linear regression model amounts to computing the parameters
\begin{align*}
\mathbf{w} = (\mathbf\Phi^\top \mathbf\Phi)^{-1} \mathbf\Phi^\top \mathbf y,
\end{align*}
where $\mathbf\Phi$ is a matrix containing some transformed version of the inputs in its rows (for more details, see sec. 2.2 of the lecture notes).

**Exercise 2.** Implement the linear regression model using the formulae derived in the lecture notes and fit a line to the dataset you generated.

In more detail:
- Compute the matrix of transformed inputs $\mathbf\Phi$ by stacking a column of ones with the training samples (`Phi_train`). You can use the [`np.vstack`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) and [`np.ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) functions. The result should look something like
```
array([[ 1. ,  0. ],
         [ 1. ,  0.2],
         [ 1. ,  0.4],
         [ 1. ,  0.6],
         [ 1. ,  0.8],
         [ 1. ,  1. ],
         [ 1. ,  1.2],
         ...
```
- Transform the test inputs in the same way (`Phi_test`).
- Implement the formula
\begin{align*}
\mathbf{w} = (\mathbf\Phi^\top \mathbf\Phi)^{-1} (\mathbf\Phi^\top \mathbf y).
\end{align*}
Note: it is very impractical to compute matrix inverses directly. Use the [`np.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) function instead. You can transpose matrices with `Phi_train.T` and perform matrix multiplication with the `@` operator or [`np.matmul`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html).
- Compute the predictions for the test inputs using the formula
\begin{align*}
\mathbf y_{\text{test}} = \mathbf\Phi_{\text{test}}\mathbf w
\end{align*}
- Plot the results using [`plt.scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) for the training dataset and [`plt.plot`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) for the test inputs and predictions.

>**_NOTE:_** Since the matrix $\mathbf\Phi^\top\mathbf\Phi$ is symmetric and positive definite, an even more efficient implementation would use a Cholesky decomposition and solution (*e.g.* [`scipy.linalg.cho_factor`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cho_factor.html#scipy.linalg.cho_factor) and [`scipy.linalg.cho_solve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cho_solve.html)). Give it a try if you want.

In [ ]:
# Compute Phi, Phi_test, w and y_test. Plot the results.



## Nonlinear regression

In this exercise, we slightly modify the transformation to perform polynomial regression; everything else stays the same. First we generate a nonlinear dataset.

**Exercise 3.** Generate a nonlinear dataset.

In more detail:

- The inputs are the same as in the linear case.
- Generate the outputs as $(x-9)\cdot(x-6)\cdot(x-1)$ with some additional Gaussian noise (scale it up to have $\sigma \sim 5$ for it to be a bit more challenging).
- Plot the dataset.

In [ ]:
# Keep x_train and x_test; generate y_train and plot the dataset.



**Exercise 4.** Modify your algorithm to perform polynomial regression with cubic polynomials and demonstrate it on the nonlinear dataset. Recall that we only need to modify the transformation of the inputs, i.e. for an input $x_i$, we have
\begin{align*}
\phi: x_i \mapsto \left[1, x_i, x_i^2, x_i^3\right]^\top .
\end{align*}

In more detail:

- Generate the matrix $\mathbf\Phi$ containing the transformed training inputs in its rows. It should look something like
```
array([[1.   , 0.   , 0.   , 0.   ],
         [1.   , 0.2  , 0.04 , 0.008],
         [1.   , 0.4  , 0.16 , 0.064],
         [1.   , 0.6  , 0.36 , 0.216],
         [1.   , 0.8  , 0.64 , 0.512],
         [1.   , 1.   , 1.   , 1.   ],
         [1.   , 1.2  , 1.44 , 1.728],
         ...
```
Note: you can do this relatively painlessly with the [`np.power.outer`](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.outer.html) or the [`np.vander`](https://numpy.org/doc/stable/reference/generated/numpy.vander.html) function.
- Do the same with the test inputs.
- Copy the code from the linear exercise and perform the nonlinear regression.
- Plot the results as in the previous case.

In [ ]:
# Compute Phi, Phi_test, w and y_test. Plot the results.



## Maximum a posteriori estimation

Recall that the maximum a posteriori estimation leads to the regularized version of (non)linear regression. The only modification is an additional term at the computation of $\mathbf w$, namely
\begin{align*}
\mathbf{w} = (\mathbf\Phi^\top \mathbf\Phi + \lambda \mathbf I)^{-1} \mathbf\Phi^\top \mathbf y.
\end{align*}

**Exercise 5.** Modify your algorithm to include regularization and do a couple of curve fittings with different $\lambda$ s.

In more detail:
- Include the additional term with using [`np.eye`](https://numpy.org/devdocs/reference/generated/numpy.eye.html) for the identity matrix.
- Plot the results using $\lambda = 0, 1, 10, 100$ and observe the effect of the regularization term.

In [ ]:
# One row and 4 columns -> ax is a 1d array with 4 Axes objects
f, axs = plt.subplots(1, 4, figsize=(16, 4))

# - using python's "zip" function to iterate over the values of lambda
#   and the returned Axes array simultaneously
# - to get λ, type \lambda and press ctrl+space (or command+space on Mac)
#   in a running colab (otherwise there's no autocomplete)
for ax, λ in zip(axs, [0, 1, 10, 100]):
  # Compute Phi, Phi_test, w and y_test.

  #ax.scatter(...)
  #ax.plot(...);

How does the regularization coefficient $\lambda$ affect the fit? Write your answer below.

**Answer:**

## Linear regression on a real-world dataset

**Exercise 6.** Demonstrate linear regression on `scikit-learn`'s `diabetes` dataset. In more detail:

- Load the dataset using `load_diabetes` from `sklearn.datasets`.
- Split the data into a training and a test set using [`train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) from `sklearn.model_selection` (use a random $80\%$-$20\%$ split).
- Transform the samples and train a basic linear regression model manually by copying your code from the previous sections.
- Train a linear regression model using [`sklearn.linear_model.LinearRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) (you will need the `fit()` and `predict()` methods).
- Evaluate and compare the predictive performance of the models using the root mean squared error metric. The two should give the same result.

In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

data = load_diabetes()
x,y = data.data, data.target

# Perform train-test split



In [ ]:
# Perform linear regression manually


# Compute RMSE
rmse_manual = ...

In [ ]:
# Perform linear regression using scikit-learn

# Compute RMSE
rmse_sklearn = ...

In [ ]:
print("RMSE (manual): {:.4f}, RMSE (sklearn): {:.4f}".format(rmse_manual, rmse_sklearn))

## Homework Assignment

**Homework assignment.** Building on Exercise 3, this task involves evaluating polynomials of degrees 0, 1, 2, 3, 4, 5, and 6 using both the test and training datasets provided (note that the synthetic data was generated by a model of degree 3). Additionally, you are required to create random training datasets of size 20 and compute the "bias" and "variance" for each class of models.

Your results should be presented in a bias-variance plot, which will display the bias, variance, and total error for each polynomial degree. The x-axis of the plot should represent the complexity of the models, indicated by the degree of the polynomials.